### ISSUE TITLE
Button Menu Download

### ISSUE THREAD

**Issue by montanojd** [Djadweb/React-Native-Wallpaper-App#1]
Hello, congrats for a great code, i have an issue,  When I press any menu button, I get a message that the image is downloaded, but the image does not appear on the device downloaded.
![image](https://user-images.githubusercontent.com/60124037/174841498-de8ed631-9515-46c4-ab0f-9de707193ae9.png)

**Comment by Djadweb** [comment]
Hello @montanojd, thank you for reporting the issue
I didn't finish the download functionality yet, still in Progress. But will update it soon.

**Comment by montanojd** [comment]
Great, Thanks for Reply i'll be waiting the update.
